# This file was generated by GoReleaser. DO NOT EDIT.
cask "wtman" do
  postflight_steps do
    on_macos do
      run "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "wtman"], chdir: "."
    end
  end

  version "0.9.1"

  on_macos do
    on_arm do
      sha256 "d555f7e03eb53236dcf829ecefd355215cf2222ca883a5507e5b8f5742f10705"
      url "https://github.com/alexiezhov/wtman/releases/download/v#{version}/wtman_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "d202680a394e7dcec1f2a4cc5d8dfba9f401c39bc36cdaab933df39dd1422d38"
      url "https://github.com/alexiezhov/wtman/releases/download/v#{version}/wtman_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "0cfd5085763a40ee524a8a438ce5d777437922b651904be3396b616965e7a4e3"
      url "https://github.com/alexiezhov/wtman/releases/download/v#{version}/wtman_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "834a879bf142cdf81d066317d2db5abb89e455861e27c4e7818f193bd4f63ff8"
      url "https://github.com/alexiezhov/wtman/releases/download/v#{version}/wtman_#{version}_linux_amd64.tar.gz"
    end
  end

  name "wtman"
  desc "Multi-repo git worktree manager with an interactive TUI and CLI"
  homepage "https://github.com/alexiezhov/wtman"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "wtman"

  # No zap stanza required
end
