# This file was generated by GoReleaser. DO NOT EDIT.
cask "wtman" do
  version "0.9.0"

  on_macos do
    on_intel do
      sha256 "840cadb7941cb8b156e5ccb97e238f8ba75e67a746c9f67ad276960c4b1be808"
      url "https://github.com/alexiezhov/wtman/releases/download/v#{version}/wtman_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "3f90884bec0fd65cfffae08e252a025dac9bcf586745bf8bdf837aed5ed1019d"
      url "https://github.com/alexiezhov/wtman/releases/download/v#{version}/wtman_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "dc1400e009b6d8c81551e6e36b615db27318e8c42d5cc7d5aba2d0e3825ce744"
      url "https://github.com/alexiezhov/wtman/releases/download/v#{version}/wtman_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "77ddb4a3b9f5633d7adef82fde99e0432ae742c933a8df92670ce5a2233f5dd8"
      url "https://github.com/alexiezhov/wtman/releases/download/v#{version}/wtman_#{version}_linux_arm64.tar.gz"
    end
  end

  name "wtman"
  desc "Multi-repo git worktree manager with an interactive TUI and CLI"
  homepage "https://github.com/alexiezhov/wtman"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "wtman"

  postflight_steps do
    on_macos do
      run "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "wtman"], chdir: "."
    end
  end

  # No zap stanza required

end
