# This file was generated by GoReleaser. DO NOT EDIT.
cask "wtman" do
  version "0.8.0"

  on_macos do
    on_intel do
      sha256 "52f21be2120289796cc134d4e1ab98a27c35066887575d90bad6a0dc56e251ed"
      url "https://github.com/alexiezhov/wtman/releases/download/v#{version}/wtman_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "4c362aca02573d5f946da263726d11b8f8696da724116e9bae7fba79d39fbb12"
      url "https://github.com/alexiezhov/wtman/releases/download/v#{version}/wtman_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "f0cc51efd8b270c2a15231b5ad0fdb6627d65688b51408edf444ff19c32e9a7e"
      url "https://github.com/alexiezhov/wtman/releases/download/v#{version}/wtman_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "cf075dbfe1527b1774e06682e6bf56f3369a52d91d1a2532067b3fb97ec291de"
      url "https://github.com/alexiezhov/wtman/releases/download/v#{version}/wtman_#{version}_linux_arm64.tar.gz"
    end
  end

  name "wtman"
  desc "Multi-repo git worktree manager with an interactive TUI and CLI"
  homepage "https://github.com/alexiezhov/wtman"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "wtman"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/wtman"]
    end
  end

  # No zap stanza required

end
